target("SessionManager")
    set_kind("binary")
    add_files("src/*.cpp")
    add_deps("workflow_manager")
    add_deps("acquisition_module")
    add_deps("echo_view_model")
    add_deps("domain_model")
    add_deps("common_caf")
    add_links("caf_core", "caf_io")
    add_includedirs("include", {public = true})

