target("session_manager")
    set_kind("binary")
    add_files("src/*.cpp")
    add_deps("workflow_manager")
    add_deps("echo_view_model")
    add_deps("domain_model")
    add_deps("common_caf")
    add_packages("actor-framework", {components = {"caf_core", "caf_io"}})
    add_includedirs("include")
