target("SessionManager")
    set_kind("binary")
    add_files("src/*.cpp")
    add_deps("WorkflowManager")
    add_deps("EchoViewModel")
    add_deps("DomainModel")
    add_deps("CommonCAF")
    add_packages("actor-framework", {components = {"caf_core", "caf_io"}})
    add_includedirs("include")
