pipeline {
    agent {
        label 'Linux'
    }
    stages {
        stage('Build Debug') {
            steps {
                script {
                    sh '''
                        xmake update
                        xmake config -m debug
                        xmake build
                    '''
                }
            }
        }
        stage('Build Release') {
            steps {
                script {
                    sh '''
                        xmake update
                        xmake config -m release
                        xmake build
                    '''
                }
            }
        }
        stage('Unit Test') {
            steps {
                script {
                    sh '''
                        xmake test
                    '''
                }
            }
        }
    }
}