pipeline {
    agent {
        label 'Linux'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Config Debug') {
            steps {
                script {
                    sh '''
                        xmake global --clean --ccache=false --theme=plain
                        xmake repo --update --verbose --diagnosis --yes
                        xmake config -m debug
                    '''
                }
            }
        }
        stage('Build Debug') {
            steps {
                script {
                    sh '''
                        xmake build
                    '''
                }
            }
        }
        stage('Unit Test Debug') {
            steps {
                script {
                    sh '''
                        xmake test
                    '''
                }
            }
        }
        stage('Config Release') {
            steps {
                script {
                    sh '''
                        xmake config -m release
                    '''
                }
            }
        }
        stage('Build Release') {
            steps {
                script {
                    sh '''
                        xmake build
                    '''
                }
            }
        }
        stage('Unit Test Release') {
            steps {
                script {
                    sh '''
                        xmake test
                    '''
                }
            }
        }
    }
}